// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRoJg6Ez4LgitHgbyTOMrNBI6uBZrQdI',
    appId: '1:1052532979080:web:f746e498e3aa54af80363d',
    messagingSenderId: '1052532979080',
    projectId: 'clone-344be',
    authDomain: 'clone-344be.firebaseapp.com',
    storageBucket: 'clone-344be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDDY0-L0HWtc0bSpP9dxYAsTo0FNBMSUI',
    appId: '1:1052532979080:android:1e0ba5bec034476580363d',
    messagingSenderId: '1052532979080',
    projectId: 'clone-344be',
    storageBucket: 'clone-344be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmmpZTSUGkU_Dy8Meav1rcQHmt2jLFiDg',
    appId: '1:1052532979080:ios:e27e30486b7e4e5e80363d',
    messagingSenderId: '1052532979080',
    projectId: 'clone-344be',
    storageBucket: 'clone-344be.appspot.com',
    iosClientId: '1052532979080-3us2higoi7atrct3tgih3dpdm6l0u4k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazoneClone',
  );
}
